### ISSUE TITLE
General VLAN usability and issues

### ISSUE THREAD

**Issue by wblackcenic** [GlobalNOC/VCE#109]
Please let me know if you'd like me to split out these issues.

- When incorrectly creating a VLAN, an error message is displayed as would be expected. However, the message says "Unable to add circuit to network model", which isn't very helpful to an end user as to what exactly the issue is.  Better error reporting would be nice.  There was another time I tried deleting a VLAN and an error was reported as "1", and the delete process did not succeed.

- When creating a VLAN, you should not be able to create a VLAN with the same two endpoints.

- Would be nice to have the ability to delete two or more VLAN's at one time

- Under VLANs, the Commands drop-down box should automatically revert back to the blank "no command" field whenever any option is chosen.  There are some general usability issues in which commands get "stuck".  The only way to "unstick" the drop down is to choose another option and then go back to the one you were on.

- There should be a confirmation when deleting VLANs, as you can accidentally delete a VLAN with the current setup.

- Ran into another issue in which VCE deleted a VLAN from its database but it still shows up on the switch.

- The first time running "Show vlan statistics" resulted in the correct result being displayed.  When I clicked on the same command again, it presented an error: "Workgroup not authorized for command show vlan statistics on switch", even though I had just successfully run the command.

**Comment by jonstout** [comment]
Linking fix for unexpected error messages of "1": https://github.com/GlobalNOC/GRNOC-RabbitMQ/pull/40

**Comment by jonstout** [comment]
Unexpected behavior related to param validation is addressed in #111

**Comment by jonstout** [comment]
The topics raised in this issue have been addressed or broken out into separate issues.
