### ISSUE TITLE
access permissions when more than workgroup are defined

### ISSUE THREAD

**Issue by sbellamine** [GlobalNOC/VCE#168]
<port name="ethernet 3/1" owner="admin">
      <tags start="100" end="199" workgroup="admin"/>	
      <tags start="205" end="205" workgroup="admin"/>
      <tags start="201" end="201" workgroup="testing"/>
    </port>

 <workgroup name="admin" admin="1" description="admin workgroup">
    <user id="user1" name="user1" email="admin@localhost" />
    <user id="user2" name="user2" email="admin@localhost" />
  </workgroup>

  <workgroup name="testing" admin="" description="testing workgroup">
    <user id="user3" />
    <user id="sbellamine" />
    <user id="ops"  />
  </workgroup>

Issue: users under workgroup testing are allowed vlans 2-4094 even though the access policy should only allow them access to vlan 201. 
I did some troubleshooting and it looks like the issue has to be with having more than workgroup block: if I made workgroup testing the first workgroup listed, access permissions work as configured.

**Comment by ajragusa** [comment]
Can you send us the relevant config statements so we can test exactly your use case to replicate.

Thanks
A.J.

**Comment by sbellamine** [comment]
Please see relevant statements from the config and a more detailed description of the issue:

<port name="ethernet 3/1" owner="admin">
      <tags start="100" end="199" workgroup="admin"/>	
      <tags start="205" end="205" workgroup="admin"/>
      <tags start="201" end="201" workgroup="testing"/>
    </port>

<workgroup name="admin" admin="1" description="admin workgroup">
    <user id="cenic" name="cenic" email="admin@localhost" />
    <user id="dave" name="dave" email="admin@localhost" />
  </workgroup>


  <workgroup name="testing" admin="" description="testing workgroup">
    <user id="will" />
    <user id="sbellamine" />
    <user id="ops"  />
  </workgroup>


- Login as user sbellamine
- For port Ethernet3/1, I should only be allowed to provision vlan201.
But when I go the “Ports” or “vlans” tabs, the tool is showing that I have access to vlans 2-4094.
