### ISSUE TITLE
commands under the VLANS section are not available when user is not an  admin user

### ISSUE THREAD

**Issue by sbellamine** [GlobalNOC/VCE#177]
- Logged in as user “user1” - user1 does not have admin priviledges
- Under the “VLANS”  tab, I select  a vlan. Under “Commands”, commands such as “show vlan” are not available for the selected vlan.
- Note: when logged in as an admin user, the issue is not present.

- Please see the relevant portion of the config:
<vlan>
        <command method_name='show_vlan' type='show' name='show vlan' interaction='cli' description='show the vlan details'>
          <cmd>show vlan [% vlan_id %]</cmd>
        </command>
        <command method_name='show_vlan_statistics' type='show' name='show vlan statistics' interaction='cli' description='shows the vlans interfaces and statistics'>
          <cmd>show vlan [% vlan_id %] statistics</cmd>
        </command>
        <command method_name='show_spanning_tree_vlan' type='show' name='show spanning-tree vlan' interaction='cli' description='shows the vlans spanning-tree'>
          <cmd>show spanning-tree vlan [% vlan_id %]</cmd>
        </command>
      </vlan>
    </commands>

    
    <port name="ethernet 1/1" owner="admin">
      <tags start="1" end="99" workgroup="admin"/>
      <tags start="100" end="199" workgroup="user1"/>
      <tags start="200" end="299" workgroup="user2"/>
    </port>
    <port name="ethernet 3/1" owner="user1">
      <tags start="100" end="199" workgroup="user1"/>
    </port>
    <port name="ethernet 3/2" owner="user2">
      <tags start="200" end="299" workgroup="user2"/>
    </port>
  </switch>

**Comment by sbellamine** [comment]
Re-pasting the relevant section of the config:

<vlan>
        <command method_name='show_vlan' type='show' name='show vlan' interaction='cli' description='show the vlan details'>
          <cmd>show vlan [% vlan_id %]</cmd>
        </command>
        <command method_name='show_vlan_statistics' type='show' name='show vlan statistics' interaction='cli' description='shows the vlans interfaces and statistics'>
          <cmd>show vlan [% vlan_id %] statistics</cmd>
        </command>
        <command method_name='show_spanning_tree_vlan' type='show' name='show spanning-tree vlan' interaction='cli' description='shows the vlans spanning-tree'>
          <cmd>show spanning-tree vlan [% vlan_id %]</cmd>
        </command>
      </vlan>
    </commands>

    
    <port name="ethernet 1/1" owner="admin">
      <tags start="1" end="99" workgroup="admin"/>
      <tags start="100" end="199" workgroup="user1"/>
      <tags start="200" end="299" workgroup="user2"/>
    </port>
    <port name="ethernet 3/1" owner="user1">
      <tags start="100" end="199" workgroup="user1"/>
    </port>
    <port name="ethernet 3/2" owner="user2">
      <tags start="200" end="299" workgroup="user2"/>
    </port>

**Comment by jonstout** [comment]
Can you verify that your specified commands are configured to allow for all users? You command definition should include `user_type='user'` per https://github.com/GlobalNOC/VCE/wiki/Permissions.

**Comment by jonstout** [comment]
This was resolved after adding user_type.
