### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by ajragusa** [GlobalNOC/VCE#87]
- break up [name description and status] and [your vlans, and your ports] into separate columns to 
- save vertical space on large screens
- Make submit buttons smaller for large screens
- Command drop down should show context (ie... selected port/vlan)
- Under workgroup details, add spaces between each user

**Comment by jonstout** [comment]
- break up [name description and status] and [your vlans, and your ports] into separate columns to save vertical space on large screens
- Under workgroup details, add spaces between each user

The above items are pretty straightforward and can be completed in the same pull req.

- Make submit buttons smaller for large screens

This has already been addressed.

The remaining issue will take a bit more work. I've gone ahead and created a separate issue to track its progress.
