### ISSUE TITLE
Unable to create / edit VLAN

### ISSUE THREAD

**Issue by wblackcenic** [GlobalNOC/VCE#91]
Neither the Create or Edit VLAN functions appear to be working.  Either that or our VM needs further re-configuring.

The following logs are being thrown:

[Fri Dec 01 14:52:32.233321 2017] [cgi:error] [pid 15949] [client 207.62.80.204:57395] AH01215: Use of uninitialized value $pattern in regexp compilation at /usr/share/perl5/vendor_perl/GRNOC/WebService/Method.pm line 613., referer: http://137.164.55.83/vce/create.html
[Fri Dec 01 14:52:32.233381 2017] [cgi:error] [pid 15949] [client 207.62.80.204:57395] AH01215: Use of uninitialized value $mime_type in lc at /usr/share/perl5/vendor_perl/GRNOC/WebService/Method.pm line 549., referer: http://137.164.55.83/vce/create.html
[Fri Dec 01 14:52:32.236222 2017] [cgi:error] [pid 15949] [client 207.62.80.204:57395] AH01215: Use of uninitialized value $params{"vlan_id"} in concatenation (.) or string at /usr/share/perl5/vendor_perl/VCE/NetworkModel.pm line 140., referer: http://137.164.55.83/vce/create.html
[Fri Dec 01 14:52:32.236825 2017] [cgi:error] [pid 15949] [client 207.62.80.204:57395] AH01215: Couldn't open: Permission denied at /usr/share/perl5/vendor_perl/VCE/NetworkModel.pm line 91., referer: http://137.164.55.83/vce/create.html
[Fri Dec 01 14:56:37.581353 2017] [cgi:error] [pid 16132] [client 207.62.80.204:57402] AH01215: Couldn't open: Permission denied at /usr/share/perl5/vendor_perl/VCE/NetworkModel.pm line 91., referer: http://137.164.55.83/vce/edit.html
[Fri Dec 01 14:56:37.584083 2017] [cgi:error] [pid 16132] [client 207.62.80.204:57402] AH01215: Log4perl: Seems like no initialization happened. Forgot to call init()?, referer: http://137.164.55.83/vce/edit.html
[Fri Dec 01 14:56:37.589008 2017] [cgi:error] [pid 16132] [client 207.62.80.204:57402] End of script output before headers: provisioning.cgi, referer: http://137.164.55.83/vce/edit.html

**Comment by jonstout** [comment]
You're hitting a permissions error with Apache. To fix this you'll need to run the following commands and then restart apache. That should be enough to get you past this.
```
sudo chown vce:vce /var/run/vce/network_model.json
sudo chmod 664 /var/run/vce/network_model.json
/usr/sbin/usermod -a -G vce apache
```
