### ISSUE TITLE
Improved login credential security

### ISSUE THREAD

**Issue by wblackcenic** [GlobalNOC/VCE#93]
To improve security, the username and password for the network device credentials should not be stored in clear-text in the access_policy.xml file.

**Comment by ajragusa** [comment]
Hi Will do you have a proposal for how to do this?  We could use some salt type of configuration, but then it feels like we have only 1 layer of indirection....

Could we instead provide a better security policy for access_policy.xml such that only root/vce can read the file be a sufficient solution?

**Comment by wblackcenic** [comment]
I have two thoughts on this.  First, if we could store the credentials in another file that are both permissions protected as well as encrypted, that would be the best option.  I'm thinking something like the .htpasswd file for HTTPD.   

If this isn't an option, something like salt applied to the username and password in access_policy.xml would also suffice.  

Thoughts?  We need to ensure that a comprised machine doesn't result in compromised network equipment as well.

**Comment by jonstout** [comment]
You can now define passwords in `/etc/vce/password.json`. The permissions on the file allow only the root user to read or write the file. Be sure to remove the existing credentials from `/etc/vce/access_policy.xml`.

```
{
  "switch.name": {
    "username": "username",
    "password": "password"
  }
}
```
