### ISSUE TITLE
Improved access_policy.xml syntax troubleshooting

### ISSUE THREAD

**Issue by wblackcenic** [GlobalNOC/VCE#94]
If a configuration error is made on the access_policy.xml file, VCE fails to start but doesn't give an obvious reason why.  This is obviously an issue of the end-user, but we're unable to determine which line of .XML file is causing the problem and therefore it's difficult to troubleshoot, especially if a lot of changes have been made.  Would it be possible to pass this configuration file through an XML syntax parser first that would then provide the user with a starting point of where to fix the issue?

**Comment by ajragusa** [comment]
Yes we need XML schema validation... so we need to write an XSD for our Schema.  Then we need to on startup validate the XML to the schema and send a human readable error indicating what in the configuration is invalid

**Comment by ajragusa** [comment]
Move the login credentials from the access policy.xml file, and make the new file so that only root/vce can read it.
