### ISSUE TITLE
Must select workgroup before switch operational status shown

### ISSUE THREAD

**Issue by wblackcenic** [GlobalNOC/VCE#95]
When logging in with a non-admin user, you must manually select your workgroup before the operational status of the switch shows.  I believe Jonathan said this was a previous bug but it may still be present.  This issue does not happen for admin users.

**Comment by wblackcenic** [comment]
This may be a duplicate of:

https://github.com/GlobalNOC/VCE/issues/81

**Comment by ajragusa** [comment]
It is a dupe of #81 so I will close this!
